[workspace]
authors = ["szhhlionhao <szhhlionhao@qq.com>"]
channels = ["conda-forge"]
name = "kento-shi-network"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.8"

[tasks]

[dependencies]
python = ">=3.11"
pandas = ">=3.0.3"
python-dotenv = ">=1.0"
numpy = ">=2.5.0"
transformers = ">=5.12.1"
networkx = ">=3.6.1,<4"
matplotlib = ">=3.11.0,<4"
seaborn = ">=0.13.2,<0.14"
scipy = ">=1.18.0,<2"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu128"]

[pypi-dependencies]
torch = ">=2.0"
python-louvain = ">=0.16, <0.17"
